name: ai_app_jam
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  lottie: ^1.2.0
  flutter:
    sdk: flutter

  firebase_core: ^2.25.4
  firebase_auth: ^4.17.4
  cloud_firestore: ^4.15.2
  cupertino_icons: ^1.0.6
  google_generative_ai:
  intl:
  flutter_dotenv: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0


flutter:

  uses-material-design: true

  fonts:
    - family: Pacifico
      fonts:
        - asset: assets/fonts/Pacifico-Regular.ttf

  assets:
     - .env
     - assets/image1_0.jpg
     - assets/cooking_man.jpg
     - assets/grandma_cooking.jpg
     - assets/family_cooking.jpg
     - assets/animations/foodAnimation.json


